[colors.primary]
  background = '#282828'
  foreground = '#ebdbb2'
[colors.normal]
  black =   '#3c3836'
  red =     '#cc241d'
  green =   '#98971a'
  yellow =  '#d79921'
  blue =    '#458588'
  magenta = '#b16286'
  cyan =    '#689d6a'
  white =   '#d5c4a1'
[colors.bright]
  black =   '#504945'
  red =     '#cc241d'
  green =   '#98971a'
  yellow =  '#d79921'
  blue =    '#458588'
  magenta = '#b16286'
  cyan =    '#689d6a'
  white =   '#ebdbb2'
