[manager]
bg = "#1d2021"
fg = "#d4be98"

[status]
normal_fg = "#ddc7a1"
normal_bg = "#32302f"
info_fg = "#7daea3"
warning_fg = "#d8a657"
error_fg = "#ea6962"

[selection]
fg = "#1d2021"
bg = "#7daea3"

[marker]
fg = "#d8a657"
bg = "#1d2021"

[preview]
bg = "#32302f"
fg = "#ddc7a1"
