[colors.primary]
  background = '#1d2021'
  foreground = '#d4be98'
[colors.normal]
  black =   '#928374'
  red =     '#ea6962'
  green =   '#a9b665'
  yellow =  '#d8a657'
  blue =    '#7daea3'
  magenta = '#d3869b'
  cyan =    '#89b482'
  white =   '#ddc7a1'
[colors.bright]
  black =   '#a89984'
  red =     '#ea6962'
  green =   '#a9b665'
  yellow =  '#d8a657'
  blue =    '#7daea3'
  magenta = '#d3869b'
  cyan =    '#89b482'
  white =   '#d4be98'
