[colors.primary]
  background = '#1a1b26'
  foreground = '#c0caf5'
[colors.normal]
  black =   '#1a1b26'
  red =     '#f7768e'
  green =   '#9ece6a'
  yellow =  '#e0af68'
  blue =    '#7aa2f7'
  magenta = '#bb9af7'
  cyan =    '#7dcfff'
  white =   '#a9b1d6'
[colors.bright]
  black =   '#16161e'
  red =     '#f7768e'
  green =   '#9ece6a'
  yellow =  '#e0af68'
  blue =    '#7aa2f7'
  magenta = '#bb9af7'
  cyan =    '#7dcfff'
  white =   '#c0caf5'
[colors.cursor]
  text =    '#1a1b26'
  cursor =  '#a9b1d6'
[colors.selection]
  text =        '#1a1b26'
  background =  '#414868'
