[colors.primary]
  background = '#1a1b26'
  foreground = '#c0caf5'
[colors.normal]
  black =   '#32344a'
  red =     '#f7768e'
  green =   '#9ece6a'
  yellow =  '#e0af68'
  blue =    '#7aa2f7'
  magenta = '#ad8ee6'
  cyan =    '#449dab'
  white =   '#787c99'
[colors.bright]
  black =   '#32344a'
  red =     '#f7768e'
  green =   '#9ece6a'
  yellow =  '#e0af68'
  blue =    '#7aa2f7'
  magenta = '#ad8ee6'
  cyan =    '#449dab'
  white =   '#787c99'
