[flavor]
dark = "gruvbox-dark"

# [mgr]
# # Background / Foreground utama
# bg = "#282828"
# fg = "#ebdbb2"
#
# # Highlight file terpilih
# selected = { fg = "#282828", bg = "#d79921", bold = true }
#
# # Warna untuk jenis file
# directory  = { fg = "#458588", bold = true }  # blue
# executable = { fg = "#98971a" }               # green
# link       = { fg = "#b16286" }               # magenta
# socket     = { fg = "#d3869b" }               # bright magenta
# fifo       = { fg = "#cc241d" }               # red
#
# # File states
# hidden     = { fg = "#928374" }               # bright black
# error      = { fg = "#fb4934", bold = true }  # bright red
#
# [status]
# # Status bar di bawah
# bg = "#3c3836"
# fg = "#ebdbb2"
# info = { fg = "#d79921" }     # yellow
# success = { fg = "#b8bb26" }  # bright green
# warning = { fg = "#fabd2f" }  # bright yellow
# error = { fg = "#fb4934" }    # bright red
#
# [preview]
# # Panel preview
# bg = "#1d2021"
# fg = "#ebdbb2"
#
# [tab]
# # Tab bar
# active   = { fg = "#282828", bg = "#d79921", bold = true }
# inactive = { fg = "#a89984", bg = "#3c3836" }
#
