package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type PaletteFile struct {
	Palette map[string]string `yaml:"palette"`
}

type SemanticFile struct {
	Semantic map[string]any `yaml:"semantic"`
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func readYAML[T any](path string, out *T) {
	b, err := os.ReadFile(path)
	must(err)
	must(yaml.Unmarshal(b, out))
}

func resolve(node any, palette map[string]string, path string) any {
	switch v := node.(type) {
	case map[string]any:
		out := map[string]any{}
		for k, val := range v {
			out[k] = resolve(val, palette, path+"."+k)
		}
		return out
	case string:
		hex, ok := palette[v]
		if !ok {
			panic(fmt.Sprintf("unknown palette key '%s' at %s", v, path))
		}
		return hex
	default:
		panic("invalid semantic value at " + path)
	}
}

func write(path, content string) {
	must(os.MkdirAll(filepath.Dir(path), 0o755))
	must(os.WriteFile(path, []byte(strings.TrimSpace(content)+"\n"), 0o644))
}

/* =========================
   GENERATORS
   ========================= */

func genNvim(c map[string]any) {
	n := c["nvim"].(map[string]any)
	bg := n["background"].(map[string]any)
	fg := n["foreground"].(map[string]any)
	t := n["text"].(map[string]any)
	s := n["state"].(map[string]any)
	a := n["accent"].(map[string]any)

	write(
		os.ExpandEnv("../../config/nvim/lua/colors/default.lua"),
		fmt.Sprintf(`
---@type ZlColors
---@return ZlColors
return {
  bg_primary       = "%s",
  bg_secondary     = "%s",
  bg_tertiary      = "%s",

  fg_primary       = "%s",
  fg_secondary     = "%s",

  text_muted       = "%s",
  text_faint       = "%s",

  error            = "%s",
  warning          = "%s",
  info             = "%s",
  hint             = "%s",

  accent_primary   = "%s",
  accent_secondary = "%s",
  accent_tertiary  = "%s",
}
`,
			bg["primary"],
			bg["secondary"],
			bg["tertiary"],

			fg["primary"],
			fg["secondary"],

			t["muted"],
			t["faint"],

			s["error"],
			s["warning"],
			s["info"],
			s["hint"],

			a["primary"],
			a["secondary"],
			a["tertiary"],
		),
	)
}

func genAlacritty(c map[string]any) {
	bg := c["background"].(map[string]any)
	fg := c["foreground"].(map[string]any)
	s := c["syntax"].(map[string]any)

	write(
		os.ExpandEnv("../../config/alacritty/colors.toml"),
		fmt.Sprintf(`
# Generated by pkg/colorgen (palette.yaml + semantic.yaml). Do not edit.
[colors.primary]
background = "%s"
foreground = "%s"

[colors.normal]
black   = "%s"
red     = "%s"
green   = "%s"
yellow  = "%s"
blue    = "%s"
magenta = "%s"
cyan    = "%s"
white   = "%s"

[colors.bright]
black   = "%s"
red     = "%s"
green   = "%s"
yellow  = "%s"
blue    = "%s"
magenta = "%s"
cyan    = "%s"
white   = "%s"
`,
			// primary
			bg["primary"],
			fg["primary"],

			// normal
			bg["secondary"],
			s["keyword"],
			s["string"],
			s["type"],
			s["function"],
			s["constant"],
			c["diagnostic"].(map[string]any)["hint"],
			fg["primary"],

			// bright
			bg["secondary"],
			s["keyword"],
			s["string"],
			s["type"],
			s["function"],
			s["constant"],
			c["diagnostic"].(map[string]any)["hint"],
			fg["primary"],
		),
	)
}

func genFish(c map[string]any) {
	bg := c["background"].(map[string]any)
	fg := c["foreground"].(map[string]any)
	s := c["syntax"].(map[string]any)
	d := c["diagnostic"].(map[string]any)

	// Pure prompt base colors only (pure-fish docs: every other
	// pure_color_* inherits from these). set -g: theming without
	// writing machine-local universal vars.
	write(
		os.ExpandEnv("../../config/fish/colors.fish"),
		fmt.Sprintf(`
# Generated by pkg/colorgen (palette.yaml + semantic.yaml). Do not edit.
set -g pure_color_danger '%s'
set -g pure_color_dark '%s'
set -g pure_color_info '%s'
set -g pure_color_light '%s'
set -g pure_color_mute '%s'
set -g pure_color_normal '%s'
set -g pure_color_primary '%s'
set -g pure_color_success '%s'
set -g pure_color_warning '%s'
`,
			d["error"],      // danger
			bg["primary"],   // dark
			fg["secondary"], // info
			fg["secondary"], // light
			fg["muted"],     // mute
			fg["primary"],   // normal
			s["function"],   // primary
			d["hint"],       // success
			d["warning"],    // warning
		),
	)
}

func genNiri(c map[string]any) {
	bg := c["background"].(map[string]any)
	fg := c["foreground"].(map[string]any)
	s := c["syntax"].(map[string]any)
	d := c["diagnostic"].(map[string]any)
	_ = bg

	write(
		os.ExpandEnv("../../config/niri/cfg/colors.kdl"),
		fmt.Sprintf(`// Generated by pkg/colorgen (palette.yaml + semantic.yaml). Do not edit.
layout {
    focus-ring {
        active-color "%s"
        inactive-color "%s"
        urgent-color "%s"
    }
}
`,
			s["function"], // active
			fg["muted"],   // inactive
			d["error"],    // urgent
		),
	)
}

func zellijTheme(name string, c map[string]any) string {
	bg := c["background"].(map[string]any)
	fg := c["foreground"].(map[string]any)
	s := c["syntax"].(map[string]any)

	return fmt.Sprintf(`    %s {
        fg "%s"
        bg "%s"
        black "%s"
        red "%s"
        green "%s"
        yellow "%s"
        blue "%s"
        magenta "%s"
        cyan "%s"
        white "%s"
        orange "%s"
    }
`,
		name,
		fg["primary"],                            // fg
		bg["primary"],                            // bg
		bg["secondary"],                          // black
		s["keyword"],                             // red
		s["string"],                              // green
		s["type"],                                // yellow
		s["function"],                            // blue
		s["constant"],                            // magenta
		c["diagnostic"].(map[string]any)["hint"], // cyan
		fg["secondary"],                          // white
		s["number"],                              // orange
	)
}

func genZellij(dark, light map[string]any) {
	write(
		os.ExpandEnv("../../config/zellij/themes/gruvbox.kdl"),
		`// Generated by pkg/colorgen (palette.yaml + palette-light.yaml + semantic.yaml). Do not edit.
themes {
`+zellijTheme("gruvbox", dark)+zellijTheme("gruvbox-light", light)+`}
`,
	)
}

func noctaliaVariant(c map[string]any) map[string]any {
	n := c["nvim"].(map[string]any)
	nbg := n["background"].(map[string]any)
	nfg := n["foreground"].(map[string]any)
	nfgTop := c["foreground"].(map[string]any)
	s := c["syntax"].(map[string]any)
	d := c["diagnostic"].(map[string]any)
	bgTop := c["background"].(map[string]any)

	ansi := map[string]any{
		"black":   bgTop["secondary"],
		"red":     s["keyword"],
		"green":   s["string"],
		"yellow":  s["type"],
		"blue":    s["function"],
		"magenta": s["constant"],
		"cyan":    d["hint"],
		"white":   nfgTop["primary"],
	}

	return map[string]any{
		"mPrimary":          s["function"],
		"mOnPrimary":        nbg["primary"],
		"mSecondary":        n["accent"].(map[string]any)["secondary"],
		"mOnSecondary":      nbg["primary"],
		"mTertiary":         n["accent"].(map[string]any)["primary"],
		"mOnTertiary":       nbg["primary"],
		"mError":            n["state"].(map[string]any)["error"],
		"mOnError":          nbg["primary"],
		"mSurface":          nbg["primary"],
		"mOnSurface":        nfg["primary"],
		"mSurfaceVariant":   nbg["secondary"],
		"mOnSurfaceVariant": nfg["secondary"],
		"mOutline":          nfgTop["muted"],
		"mShadow":           nbg["primary"],
		"mHover":            nbg["tertiary"],
		"mOnHover":          nfg["primary"],
		"terminal": map[string]any{
			"background":  bgTop["primary"],
			"foreground":  nfgTop["primary"],
			"cursor":      nfgTop["primary"],
			"cursorText":  bgTop["primary"],
			"selectionBg": bgTop["elevated"],
			"selectionFg": nfgTop["primary"],
			"normal":      ansi,
			"bright":      ansi,
		},
	}
}

func genNoctalia(dark, light map[string]any) {
	b, err := json.MarshalIndent(map[string]any{
		"dark":  noctaliaVariant(dark),
		"light": noctaliaVariant(light),
	}, "", "  ")
	must(err)
	write(os.ExpandEnv("../../config/noctalia/palettes/ZlGruvbox.json"), string(b))
}

/* =========================
   MAIN
   ========================= */

func main() {
	dir := os.ExpandEnv("./")

	var palette PaletteFile
	var paletteLight PaletteFile
	var semantic SemanticFile

	readYAML(filepath.Join(dir, "palette.yaml"), &palette)
	readYAML(filepath.Join(dir, "palette-light.yaml"), &paletteLight)
	readYAML(filepath.Join(dir, "semantic.yaml"), &semantic)

	resolved := resolve(semantic.Semantic, palette.Palette, "semantic").(map[string]any)
	resolvedLight := resolve(semantic.Semantic, paletteLight.Palette, "semantic").(map[string]any)

	// Optional: dump resolved.json (debugging / inspection, dark only)
	b, _ := json.MarshalIndent(resolved, "", "  ")
	_ = os.WriteFile(filepath.Join(dir, "resolved.json"), b, 0o644)

	genNvim(resolved)
	genAlacritty(resolved)
	genFish(resolved)
	genNiri(resolved)
	genZellij(resolved, resolvedLight)
	genNoctalia(resolved, resolvedLight)

	fmt.Println("✔ colors generated (nvim, alacritty, fish, niri, zellij, noctalia)")
}
