package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type PaletteFile struct {
	Palette map[string]string `yaml:"palette"`
}

type SemanticFile struct {
	Semantic map[string]any `yaml:"semantic"`
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func readYAML[T any](path string, out *T) {
	b, err := os.ReadFile(path)
	must(err)
	must(yaml.Unmarshal(b, out))
}

func resolve(node any, palette map[string]string, path string) any {
	switch v := node.(type) {
	case map[string]any:
		out := map[string]any{}
		for k, val := range v {
			out[k] = resolve(val, palette, path+"."+k)
		}
		return out
	case string:
		hex, ok := palette[v]
		if !ok {
			panic(fmt.Sprintf("unknown palette key '%s' at %s", v, path))
		}
		return hex
	default:
		panic("invalid semantic value at " + path)
	}
}

func write(path, content string) {
	must(os.MkdirAll(filepath.Dir(path), 0o755))
	must(os.WriteFile(path, []byte(strings.TrimSpace(content)+"\n"), 0o644))
}

/* =========================
   GENERATORS
   ========================= */

func genNvim(c map[string]any) {
	n := c["nvim"].(map[string]any)
	bg := n["background"].(map[string]any)
	fg := n["foreground"].(map[string]any)
	t := n["text"].(map[string]any)
	s := n["state"].(map[string]any)
	a := n["accent"].(map[string]any)

	write(
		os.ExpandEnv("../../config/nvim/lua/colors/default.lua"),
		fmt.Sprintf(`
---@type ZlColors
---@return ZlColors
return {
  bg_primary       = "%s",
  bg_secondary     = "%s",
  bg_tertiary      = "%s",

  fg_primary       = "%s",
  fg_secondary     = "%s",

  text_muted       = "%s",
  text_faint       = "%s",

  error            = "%s",
  warning          = "%s",
  info             = "%s",
  hint             = "%s",

  accent_primary   = "%s",
  accent_secondary = "%s",
  accent_tertiary  = "%s",
}
`,
			bg["primary"],
			bg["secondary"],
			bg["tertiary"],

			fg["primary"],
			fg["secondary"],

			t["muted"],
			t["faint"],

			s["error"],
			s["warning"],
			s["info"],
			s["hint"],

			a["primary"],
			a["secondary"],
			a["tertiary"],
		),
	)
}

func genAlacritty(c map[string]any) {
	bg := c["background"].(map[string]any)
	fg := c["foreground"].(map[string]any)
	s := c["syntax"].(map[string]any)

	write(
		os.ExpandEnv("../../config/alacritty/colors.toml"),
		fmt.Sprintf(`
# Generated by pkg/colorgen (palette.yaml + semantic.yaml). Do not edit.
[colors.primary]
background = "%s"
foreground = "%s"

[colors.normal]
black   = "%s"
red     = "%s"
green   = "%s"
yellow  = "%s"
blue    = "%s"
magenta = "%s"
cyan    = "%s"
white   = "%s"

[colors.bright]
black   = "%s"
red     = "%s"
green   = "%s"
yellow  = "%s"
blue    = "%s"
magenta = "%s"
cyan    = "%s"
white   = "%s"
`,
			// primary
			bg["primary"],
			fg["primary"],

			// normal
			bg["secondary"],
			s["keyword"],
			s["string"],
			s["type"],
			s["function"],
			s["constant"],
			c["diagnostic"].(map[string]any)["hint"],
			fg["primary"],

			// bright
			bg["secondary"],
			s["keyword"],
			s["string"],
			s["type"],
			s["function"],
			s["constant"],
			c["diagnostic"].(map[string]any)["hint"],
			fg["primary"],
		),
	)
}

/* =========================
   MAIN
   ========================= */

func main() {
	dir := os.ExpandEnv("./")

	var palette PaletteFile
	var semantic SemanticFile

	readYAML(filepath.Join(dir, "palette.yaml"), &palette)
	readYAML(filepath.Join(dir, "semantic.yaml"), &semantic)

	resolved := resolve(semantic.Semantic, palette.Palette, "semantic").(map[string]any)

	// Optional: dump resolved.json (debugging / inspection)
	b, _ := json.MarshalIndent(resolved, "", "  ")
	_ = os.WriteFile(filepath.Join(dir, "resolved.json"), b, 0o644)

	genNvim(resolved)
	genAlacritty(resolved)

	fmt.Println("✔ colors generated (nvim, alacritty)")
}
